--Case Study / Capstone Project

--Find the neighborhood with the highest total revenue and the average price per listing

--Compare the average price of listings in different neighborhoods

--Count the occurrences of the word "comfortable" in the comment's column

--Identify listings with a high proportion of positive reviews(comments with “great”, “comfortable” and “good”)

--Calculate the total revenue generated by each host for listings that were last reviewed within the past one year

--Find hosts with the name ‘Stan’, regardless of capitalization

--Calculate the total revenue generated by listings with a price above $700

--Find the most reviewed listing

--Find listings that were last reviewed in the last quarter of 2022

--Calculate the total revenue generated for each listing, categorizing them as "high-priced" or "low-priced" based on their price relative to the average price for their neighborhood
